gui_settings:
  title: 'ON/OFF'
  size: 3
  toggled_on:
    material: LIME_WOOL
    name: '&2&l>> &a브금 켜기 &2&l<<'
    slot: 13
    lore:
      - ''
      - '&e&l➥ &f&l우클릭시 브금을 켭니다! '
      - ''
  toggled_off:
    material: RED_WOOL
    name: '&4&l>> &c브금 끄기 &4&l<<'
    slot: 13
    lore:
      - ''
      - '&e&l➥ &f&l좌클릭시 브금을 끕니다! '
      - ''