name: ST-RegionBGM
main: net.starly.regionbgm.RegionBGMMain
author: Starly Team
website: http://starly.kr/discord

description: RegionBGM Plugin.

version: 1.0.3
api-version: 1.13

softdepend:
  - ST-Core
  - ST-Region

commands:
  bgm:
    aliases: [ 브금 ]
  regionbgm:
    aliases: [ rbgm, 구역브금 ]