name: ST-RegionBGM
main: net.starly.regionbgm.RegionBGM
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

version: 1.0
api-version: 1.16

softdepend:
  - ST-Core
  - ST-Region

commands:
  bgm:
    aliases: [브금]
  regionbgm:
    aliases: [구역브금]