name: ST-RegionBGM
main: net.starly.regionbgm.RegionBGM
author: Starly Team
website: https://discord.gg/TF8jqSJjCG
description: RegionBGM Plugin

version: 1.0.0
api-version: 1.13

softdepend:
  - ST-Core
  - ST-Region

commands:
  bgm:
    aliases: [브금]
  regionbgm:
    aliases: [구역브금]